# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ewOv3LMAPVuqk60KvCuErjMHbcnoh1Gm
"""

from .pilha import Pilha
from .fila import Fila
from .uset import Uset
from .deque import Deque
from .sset import Sset
from .filaprioridade import FilaPrioridade