# -*- coding: utf-8 -*-
"""deque

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SV6LESwKVJlDn2BhSTxU8tNhQgT2kwqd
"""

class Deque:
    def __init__(self):
        self.items = []

    def add_first(self, item):
        self.items.append(item)

    def add_last(self, item):
        self.items.insert(0,item)

    def remove_first(self):
        return self.items.pop()

    def remove_last(self):
        return self.items.pop(0)

    def size(self):
        return len(self.items)