# -*- coding: utf-8 -*-
"""fila_aleatoria

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EoKR5ptMF5QuXVlanIpMN70Xd0aHxvc3
"""

from .fila import Fila
from random import randrange

class FilaAleatoria(Fila):
    # escreva o método remove que remove um elemento aleatório da fila
    # fique atento, pois se você remover diretamente um elemento aleatório
    # sua implementação será O(n), onde n é o tamanho da fila.
    # Você deve implementar este método de forma que ele seja O(1).
    def remove(self, i = 0):
      x=randrange(0,len(self.fila))
      return self.fila.pop(x)