# -*- coding: utf-8 -*-
"""pilha

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kXPMK7E0fP5Ov9E7iqXd5BHq-9KKpoUr
"""

class Pilha:
    def __init__(self):
        self.pilha = []
    def push(self, valor):
        self.pilha.append(valor)
    def pop(self):
        if not self.pilha:
            raise Exception("Pilha vazia")
        return self.pilha.pop()
    def vazia(self):
        return not self.pilha

    def size(self):
        return len(self.pilha)